apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ws-bridge.fullname" . }}-script
  labels:
    {{- include "ws-bridge.labels" . | nindent 4 }}
data:
  main.ts: |
{{ .Files.Get "files/main.ts" | indent 4 }}
