apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ws-bridge.fullname" . }}
  labels:
    {{- include "ws-bridge.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
